apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "33.x"
    helm:
      valuesObject:
        deployment:
          replicas: 1
        service:
          type: ClusterIP
        ports:
          web:
            port: 8000
            exposedPort: 80
          websecure:
            port: 8443
            exposedPort: 443
        ingressRoute:
          dashboard:
            enabled: true
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
        logs:
          general:
            level: INFO
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
